### ISSUE TITLE
Is the jetstream benchmark really necessary?

### ISSUE THREAD

**Issue by fabiosantoscode** [terser-js/terser#126]
It takes a very long time to run.

@kzc what are your thoughts?

**Comment by kzc** [comment]
Somewhat on-topic - the recent commit https://github.com/terser-js/terser/commit/fb40fde95a44dbe0ba29bf45c241591d68ab9229 has no accompanying tests of any kind to demonstrate its use. I'd suggest to add some `expect_stdout` regression tests. While it's good that this option is disabled by default due to it being unsafe, I think it would be prudent to rename it to give it an `unsafe_` prefix like the other non-general optimizations.

**Comment by kzc** [comment]
Most recent example of `test/jetstream.js` finding a bug in a user created PR: https://github.com/mishoo/UglifyJS2/pull/3270#issuecomment-431497653

**Comment by fabiosantoscode** [comment]
Got it
