### ISSUE TITLE
[Doc] ES versions in documentation sometimes don't exist

### ISSUE THREAD

**Issue by danwdart** [terser-js/terser#169]
**Bug report**

ECMAScript versions above 5 are known as ES2015, ES2016, ES2017, ES2018, rather than ES6, ES7, ES8, ES9 etc... according to the ES specs here:

https://www.ecma-international.org/ecma-262/6.0/index.html
https://www.ecma-international.org/ecma-262/7.0/index.html
https://www.ecma-international.org/ecma-262/8.0/index.html
https://www.ecma-international.org/ecma-262/9.0/index.html

**Comment by kzc** [comment]
This will remain as is. 

Standard ECMA-262 - 6th Edition / June 2015
...etc

I prefer using ES5/6/7/8/9 edition number nomenclature because people throw around incorrect ES20XX year references all the time for prospective ES features that haven't yet been put into an official standard.

This is not a big deal in the grand scheme of things. People can figure it out.

**Comment by kzc** [comment]
This issue can be closed.
