### ISSUE TITLE
Replace const with let (except in the global scope)

### ISSUE THREAD

**Issue by josephg** [terser-js/terser#172]
*Feature request, terser@3.10.11*

Terser keeps variables assigned using `const`. These variables should be converted to `let`, because its 2 characters shorter.

Eg this code:

```javascript
const foo = () => {
  const x = "some long string";
  bar(x)
  bar(x)
}
```

Via `terser -cmb` is virtually unchanged:

```javascript
const foo = () => {
    const o = "some long string";
    bar(o), bar(o);
};
```

It should instead become:

```javascript
const foo = () => {
    let o = "some long string";
    bar(o), bar(o);
};
```

**Comment by kzc** [comment]
This has been proposed a few times. It's not a safe transform in general - particularly with buggy code.

```
$ cat test.js
function f() {
    const a = 1;
    try {
        a = 2;
        console.log("FAIL");
    } catch (x) {
        return console.log("PASS");
    }
}
f();
```
```
$ cat test.js | node
PASS
```
```
$ cat test.js | sed 's/const/let/g'
function f() {
    let a = 1;
    try {
        a = 2;
        console.log("FAIL");
    } catch (x) {
        return console.log("PASS");
    }
}
f();
```
```
$ cat test.js | sed 's/const/let/g' | node
FAIL
```

**Comment by josephg** [comment]
Sorry - I couldn’t find an issue about it in the issue tracker. 

Reassigning a const expression is *never* valid - but I thought it was a syntax error, not a runtime error. (Why is it a runtime error?? Argh). 

The only time I could imagine this coming up is in code which did it anyway and where correct execution depends on that exception. Which should be nobody but 🤷‍♀️ I do understand the hardlined approach to correctness here.

Eh - not my project; not my call.

**Comment by kzc** [comment]
> the hardlined approach to correctness here.

That's the difference between a high quality minifier and a poor quality one. Any behavior or bug present in the Terser input should also be present in the minified output rather than incorrectly hiding it. Terser, like uglify before it, aims to produce functionally equivalent code to that of the original when run. 

> What if we check for reassignment of the variable. And only if it's not reassigned we convert to let?

By examining all `SymbolDef` `references` it ought to be possible. Would have to check for `AST_Assign` which covers simple assignment `(a = 2)` and various forms of compound assignment `(a *= 2)`, and `AST_Unary` updates such as `(--a)`, `(a++)` and `delete a`. I *think* those are the only forms affecting `const`. 

This feature should be behind a new `compress` option `const_to_let`. AFAIK multiple `const` variable declarations of the same variable name in the same scope would be a parser error, so that shouldn't be an issue. And as previously mentioned this transform must not convert top level variables from `const` to `let`.

**Comment by kzc** [comment]
> Sorry - I couldn’t find an issue about it in the issue tracker.

No worries. It may have been discussed in the old uglify-es project (from which Terser was forked) or in another forum. There was a twitter thread about it as well. There's a finite number of minification ideas.

**Comment by kzc** [comment]
I failed to consider the consequences of destructuring on `const`:

```
$ cat d.js
function f() {
    const a = 1;
    try {
        ({x: a} = {x: 2});
        console.log("FAIL");
    } catch (x) {
        return console.log("PASS");
    }
}
f();
```
```
$ cat d.js | node
PASS
```
```
$ cat d.js | sed 's/const/let/g'
function f() {
    let a = 1;
    try {
        ({x: a} = {x: 2});
        console.log("FAIL");
    } catch (x) {
        return console.log("PASS");
    }
}
f();
```
```
$ cat d.js | sed 's/const/let/g' | node
FAIL
```
There may be other ES6+ constructs that could mess up this transform as well. Would have to give it some more thought.

**Comment by josephg** [comment]
Thinking about this a bit more, if it were up to me I'd promote assignment-to-const runtime errors into compilation errors.

Terser already does not compile at all in the presence of most syntax errors. If `const-to-let` was a compression feature, people could always preserve the runtime error by turning the feature off at minification time. (Even though I can't think of any reason why anyone would explicitly prefer runtime type errors).

We could hypothetically add a mixed mode, but who would use it? Compilation failures are always better than crashes in the normal case. And in the weird case that you're explicitly assigning to const to throw, you can just turn the const-to-let feature off.

**Comment by kzc** [comment]
> promote assignment-to-const runtime errors into compilation errors

That isn't ECMAScript compliant and would require roughly the same amount of work as determining when `const` can be safely converted to `let` as [outlined above](https://github.com/terser-js/terser/issues/172#issuecomment-439704145).

**Comment by fabiosantoscode** [comment]
Agreed. We should always remain ES compliant. Although we can easily check for reassignment of the symbols if we like, and only turn to let if they're unused

**Comment by kzc** [comment]
If any of the variable `references` of a compound `const` declaration are modified just leave the statement as is rather then splitting it into a combination of `let` and `const` declarations which would be larger still. For example, this code:

```
const a = 1, b = a, c = a + b;
b++;
console.log(a, b, c);
```
should **not** be converted to:
```
let a = 1;                // don't do this
const b = a;
let c = a + b;
b++;
console.log(a, b, c);
```
The original `const` decl should be left as is. Don't be tempted to combine `let` and `const` decls due to the complexity of side effects.

**Comment by kzc** [comment]
I have an efficient implementation of `const_to_let` with `warnings` support.  Just have to write some tests.

```
$ echo 'const c = foo(); let b = bar(); console.log(a, b);' | terser -c --warn
let c=foo(),b=bar();console.log(a,b);
```
```
$ echo 'const c = foo(); let b = bar(c--); console.log(a, b);' | terser -c --warn
WARN: Assignment to constant variable c [0:1,29]
const c=foo();let b=bar(c--);console.log(a,b);
```

Transforms like this one don't save many bytes. The minified ES6 bundle of Rollup's code base is only 0.16% smaller as result - 490 bytes saved from an minified bundle size of 314157 bytes. After gzip the savings was only 0.05% - 41 bytes saved from a gzipped bundle size of 87126 bytes. The only transforms that matter are ones that eliminate entire sections of code.

**Comment by josephg** [comment]
Interesting take.

I think the savings will completely depend on the project / developer. Personally I `const` all variables that I don't modify, so its a much bigger saving for me. I just checked with a recent project I've been working on. My project minifies to 19k, and the minified output contains the `const` keyword 82 times. Replacing them with `let` changes the output size from 19814 to 19650 bytes (0.8% smaller), and it makes the gzipped output drop from 7076 to 7049 bytes - which is 0.3% smaller.

Thats not nothing, but it is pretty small in the scheme of things. I get it if you don't think this change is worth it.

**Comment by kzc** [comment]
You have a point. Although there was Rollup ES6 code in the (custom) bundle, most of it was comprised of ES5 commonjs dependencies like acorn which would reduce the `const` count considerably. 

Regarding `const_to_let`, I wonder if the "except in the global scope" constraint is necessary. What would be the use case?

**Comment by josephg** [comment]
Its the same rationale as why we don't mangle global names - changing a variable from const to let (sort of) changes the external API. Consider a page that does this:

```javascript
// bundle.js
const exposed_var = 2
```

```html
<script src='bundle.js'></script>
<script>
exposed_var = 10
</script>
```

If the bundle is minified with `const_to_let`, the page will no longer throw an exception.

**Comment by kzc** [comment]
Yeah, I thought as much. But if ES5 code was generated for the bundle - like the way the vast majority of code is shipped these days - then it'd be a global `var` anyway without such reassignment safeguards. Then shipping an ES6 bundle with global `const` would change existing behavior for polyfills and the rest. No matter.

`const_to_let` behavior could be different depending on whether `toplevel` is enabled (or indirectly enabled via `module`). If `toplevel` (`mangle` or `compress`) is enabled then `const_to_let` could replace global `const` with `let`. Otherwise the global `const`s would be kept. It's a pain, but it could be done.

**Comment by fabiosantoscode** [comment]
Since a constant shouldn't be redefined, doesn't this mean we already implement the check? It has to be a compile error. If we don't, then we should do it, and then this feature becomes really cost effective since the check is already done.

Would anyone send a pr or should I work on this?

**Comment by kzc** [comment]
These are `const` runtime errors, not syntax errors, which are trickier to reliably find - particularly with destructuring:

* https://github.com/terser-js/terser/issues/172#issuecomment-439676133
* https://github.com/terser-js/terser/issues/172#issuecomment-439707424

I have a patch [in progress](https://github.com/terser-js/terser/issues/172#issuecomment-442156430) supporting warnings. To be more efficient the check is only done in `figure_out_scope` rather than the `Compressor` and only in the first pass of `passes`. It only slows down `minify` by 1% or so. Still needs tests and [toplevel](https://github.com/terser-js/terser/issues/172#issuecomment-442602322) support.

**Comment by fabiosantoscode** [comment]
Very cool stuff!

**Comment by kzc** [comment]
Feel free to implement this. I no longer work on Terser.

**Comment by fabiosantoscode** [comment]
Given that fixing this wouldn't produce great post-gzip savings, I'm closing the issue.

**Comment by gdh1995** [comment]
Why not just add an extra switch which is default to be false to do this transformation?

I can not come up with any cases where a runtime exception of `const` will be used to control high-level code behavior dynamically. Basically, if a `const` fails the compilation, then a `let` does, too. Isn't it? Besides, code in debug mode should have warned developers such exceptions.

**Comment by justinfagnani** [comment]
One place where this would have pre- and post- compression savings is when combining variable declarations. Right now you have to take care to order declarations so that let and const variables are contiguous to end up with as many declarators per declarations as possible. With this transform we'd save a few bytes in blocks with both let and const, or where they have to be interleaved because of initializers.

**Comment by heyheyhello** [comment]
Re: https://github.com/terser/terser/issues/172#issuecomment-442250138 I absolutely understand that some projects will only see a 0.3% change, like in your case, but I see a 19% change in my gzipped size. That kills any reason to use Terser for me unfortunately. I expect others developing micro libaries (think HTM or Preact) won't be okay with such a large size change...

I think there should be option to merge const, let, and var into just var. It's also a perf bump for Safari by avoiding the TDZ, which is why esbuild does it.
