### ISSUE TITLE
This output is less terse than the input (destructuring)

### ISSUE THREAD

**Issue by sstur** [terser-js/terser#268]
**Bug report or Feature request?**
Sub-optimal code (technically not a bug I guess, but certainly unexpected behavior)

**Version (complete output of `terser -V`)**
3.10.2

**Complete CLI command or `minify()` options used**
```
echo 'let {foo} = bar;' | terser --compress --mangle --
```

**`terser` input**
```js
let {foo} = bar;
```

**`terser` output or error**
```js
let{foo:foo}=bar;
```

**Expected result**
```js
let{foo}=bar;
```

**Comment by fabiosantoscode** [comment]
If the `--ecma` option is not set to at least `--ecma 6` then it doesn't want to write just `let{foo}`. If you set `--ecma 6` or more it will be fixed.

**Comment by sstur** [comment]
Thank you for clarifying that!

**Comment by fabiosantoscode** [comment]
Terser does not stop you from adding `let` if ecma is set to 5. I'm not happy to crash when people stick a few let and const into ECMA 5 code, since sometimes people aren't in full control of their input code.

The history for this is that I implemented `let` and `const` back in UglifyJS before there was an `ecma` option. But now that all this time has passed and people might be trusting this to be the actual behaviour, I don't think it's such a good idea.
