### ISSUE TITLE
Extra parentheses around non-returned arrow functions

### ISSUE THREAD

**Issue by isiahmeadows** [terser-js/terser#281]
**Bug report or Feature request?** Feature request (but might be a bug instead)

**Version (complete output of `terser -V`)** 3.16.1

**Complete CLI command or `minify()` options used** `terser -cm`

**`terser` input**

```js
function foo(x) { let y = x; bar = () => x; return () => y++ }
```

**`terser` output or error**

```js
function foo(n){let o=n;return bar=(()=>n),()=>o++}
```

**Expected result**

```js
function foo(n){let o=n;return bar=()=>n,()=>o++}
```

Note the lack of parentheses around `()=>n`.

This also repros in these cases, very unusually:

```js
// Why isn't this just lowered into `bar=()=>n;{let foo=()=>o++;eval("foo")}`?
{ let foo; bar = () => n; foo = () => o++; eval("foo") } // Input
{let foo;bar=(()=>n),foo=(()=>o++),eval("foo")}          // Output

// Why isn't this just lowered into `bar=()=>n;` and `foo` elided entirely?
{ let foo; bar = () => n; foo = () => o++; } // Input
{let a;bar=(()=>n),a=(()=>o++)}              // Output
```

**Comment by fabiosantoscode** [comment]
Since this is just suboptimal output, let's call it an enhancement.

This has to be a change in the parenthesis code: https://github.com/terser-js/terser/blob/master/lib/output.js#L793

To answer your questions in the last code example:

1. I'm not happy to do optimisations specifically for code using anonymous blocks in the toplevel to hide block-scoped variables, since this doesn't translate well into ES5, doesn't save that many bytes and not too many people are going to realise it's possible.
2. That's another issue that's already been opened. `let` is being treated very differently from `var` at this moment.
