### ISSUE TITLE
Feature: long array optimisation

### ISSUE THREAD

**Issue by JoelEllis** [terser-js/terser#347]
**Bug report or Feature request?**
Feature: long array optimisation:

Terser should optimise long arrays of strings into single strings turned into arrays by the `.split` function. It should try to do it in as many situations where it helps as possible - ie if s string has spaces, use a different char - for example commas as the split char.

**`terser` input**

```js
var v = ["aaa", "aarp", "abarth", "abb", "abbott", // ......
  "xn--xhq521b", "xn--xkc2al3hye2a", "xn--xkc2dl3a5ee0h", "xn--y9a3aq", "xn--yfro4i67o", "xn--ygbi2ammx", "xn--zfr164b", "xxx", "xyz", "yachts", "yahoo", "yamaxun", "yandex", "ye", "yodobashi", "yoga", "yokohama", "you", "youtube", "yt", "yun",
  "za", "zappos", "zara", "zero", "zip", "zm", "zone", "zuerich", "zw"
];
```

**`terser` output or error**
```js
var v=["aaa","aarp","abarth","abb","abbott", // ......
"xn--xhq521b","xn--xkc2al3hye2a","xn--xkc2dl3a5ee0h","xn--y9a3aq","xn--yfro4i67o","xn--ygbi2ammx","xn--zfr164b","xxx","xyz","yachts","yahoo","yamaxun","yandex","ye","yodobashi","yoga","yokohama","you","youtube","yt","yun",
"za","zappos","zara","zero","zip","zm","zone","zuerich","zw"];
```
**Expected result**
```js
var v="aaa aarp abarth abb abbott " +  // ......
"xn--xhq521b xn--xkc2al3hye2a xn--xkc2dl3a5ee0h xn--y9a3aq xn--yfro4i67o xn--ygbi2ammx xn--zfr164b xxx xyz yachts yahoo yamaxun yandex ye yodobashi yoga yokohama you youtube yt yun " + 
"za zappos zara zero zip zm zone zuerich zw".split(" ");
```
**Version (complete output of `terser -V`)**
`3.17.0`
**Complete CLI command or `minify()` options used**

```js
terser({
  compress: {
    unsafe: true,
    passes: 2,
    keep_fargs: false,
    drop_console: true,
    arguments: true
  },
  mangle: {
    properties: {
      regex: /(^_)|(_$)/
    },
    toplevel: true
  },
  output: {
    beautify: false,
    preamble: '/* ' + preamble + ' */',
    safari10: true,
    webkit: true
  }
  // TODO: nameCache: {}
})
```

**Comment by derpmarine168** [comment]
In an app containing an array of every domain name, this can save more than 3k. It's worth it, and it's used in closure compiler too when it's in the same mode that turns `new Array()` into `[]`.

**Comment by isiahmeadows** [comment]
This is not safe when `String.prototype.split` is overridden in the environment. Can't say it won't get added as I don't work on Terser personally, but it almost certainly won't be enabled by default.

**Comment by fabiosantoscode** [comment]
Terser has an unsafe mode, which does turn `new Array` into `[]` (and variations of calls to the Array constructor), but this is different, since it involves creating a new string just to split it apart. It means that more memory will be used than initially required, especially if the array is very large. If the code is run multiple times this array split is run multiple times as well, allocating a lot of memory in the process.

I won't be enabling this because I don't believe in encoding data in the middle of javascript code. There was a time for that, and I did do it myself, but I believe that if you're doing that you can encode your data as a string on the serverside and figure out the proper separator.

More control to the user, less magic.

**Comment by JoelEllis** [comment]
Fair enough. Thought it might be a useful idea, because of the space it saves on download time. 

Also, from my basic understanding this will never more than double the memory usage of just an array (and the string will be GCed on the first cycle), because the string is a single box (chunk of RAM with padding around it to change the size) whilst the array has to have a box for each element to change size.
