### ISSUE TITLE
syntax error on class static property

### ISSUE THREAD

**Issue by GerholdtSchnaps** [terser-js/terser#371]
nodejs 6.9.0
terser 4.0.0
Win10 x64

terser --compress --mangle -- input.js
Parse error at input.js:LINE,COLUMN
static PROP_NAME = "Some string message.";
ERROR: Unexpected token: operator (=)

var Singleton = class
{
    static PROP_NAME = "Some string message";
    static FUNC_NAME () { return false; }
};

**Comment by Conduitry** [comment]
As far as I know, class fields are still stage 3. Historically, Terser has not implemented things until after they are officially accepted.

**Comment by fabiosantoscode** [comment]
That is correct. This is something that I personally hope never gets implemented even though I use it a lot on my day job. There's already an issue for this so I'm closing. Thanks for the report!

**Comment by Nicholas-Westby** [comment]
For anybody else who comes across this via Google like I did, it seems Terser doesn't support any properties on a class (i.e., rather than just static properties). I had an issue with a class that looked like this:

```javascript
class Whatever {
    someProperty;
}
```

And for me the error message was:

```text
Unexpected token: punc (;)
```

The fix is to just remove the property (at least in my case, as I set the property value elsewhere in the code before it gets used).

No action is necessary for anybody reading this. Just wanted to give others a heads up.
