### ISSUE TITLE
breaking change question about v4.x

### ISSUE THREAD

**Issue by LongTengDao** [terser-js/terser#421]
What does this mean? (https://github.com/terser-js/terser/blame/master/CHANGELOG.md#L47)

I can't find any info about `variables` or `scope` in the options doc.

> ## v4.0.0
> 
>  - **breaking change**: The `variables` property of all scopes has become a standard JavaScript `Map` as opposed to the old bespoke `Dictionary` object.

I'm upgrading my dependency from terser@3.16.1 to terser@4.1.4.

And, is there any other breaking changes (with 3.x) after 4.1?

Thank you!

**Comment by fabiosantoscode** [comment]
Hello @LongTengDao, the breaking change is OK for most people using Terser, it's only a breaking change for anyone who is using the Terser AST (eg if you use `Terser.parse(code)` to retrieve a Terser AST and modify it using `Terser.TreeTransformer` or walk it using `Terser.TreeWalker`).

AST_Scope's `variables` property was changed to a standard ES Map.

There are no other breaking changes, otherwise there would be another major version bump!

**Comment by LongTengDao** [comment]
I see, thank you!

**Comment by lmdc45** [comment]
I was using Terser.TreeWalker, is there any way to use it still with version 5+?

**Comment by fabiosantoscode** [comment]
No, all internal aspects of Terser have been locked up so they can be improved without major version bumps

**Comment by lmdc45** [comment]
ok, thanks - is there a plan to re-expose in a later date, or will it never be exposed again?

**Comment by fabiosantoscode** [comment]
Never again.

There are already great tools for transforming JavaScript, such as recast
